### PR TITLE
Fix #433: download the tarball from Github and untar() it, instead of unzip()

### LINKED ISSUE #433: `new_site()` fails with confusing error if path too long with Academic theme
I was trying to create a new site using blogdown with the Academic theme. I tried using both the RStudio GUI version and entering the commands in the console. In both cases I was getting an error about a file not existing when trying to unzip. I eventually tried using the same process in a different folder, higher up my path. It worked.

Everything is pretty up-to-date:

Operating system: Windows 10
Blogdown version: 0.17 (from CRAN)
R version: 3.6.2
RStudio version: 1.2.5033
Hugo version: 0.65.3

```
library(blogdown)

new_site(theme = "gcushen/hugo-academic", 
         sample = TRUE, 
         theme_example = TRUE, 
         empty_dirs = TRUE,
         to_yaml = TRUE)
```

If my project is in some long path I get the following error:

```
Error in utils::unzip(zipfile, exdir = tmpdir) : 
  cannot open file '1e0c1ec37a8f/hugo-academic-master/exampleSite/resources/_gen/assets/scss/scss/main.scss_6c95cc1249b26b124274204dbf970c34.content': No such file or directory
```

Additionally, in the variant when I try this via the RStudio GUI for creating a new Blogdown project, I get an RStudio popup titled "Error Creating Project" saying "R code execution error".

If my project is in a shorter path, the same commands run successfully, whether entered at the Console or using the RStudio 'new project' GUI.

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('blogdown')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/blogdown')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

### PR DESCRIPTION
**Pull request by yihui**
Because `unzip()` is unable to extract files in certain cases (e.g. #433).

### CODE REVIEW

File: R/hugo.R [hunk 1]
```diff
@@ -165,28 +166,32 @@ install_theme = function(
...
   dir_create('themes')
   in_dir('themes', {
-    if (theme_is_url) {
-      url = theme
-      zipfile = gsub(".+/(.+\\.zip)", "\\1", theme)
-    } else {
-      url = sprintf('https://%s/%s/archive/%s.zip', hostname, theme, branch)
-      zipfile = sprintf('%s.zip', basename(theme))
+    url = if (theme_is_url) theme else {
+      sprintf('https://%s/%s/archive/%s.tar.gz', hostname, theme, branch)
```
Comment (yihui) [inline R/hugo.R:183]: @ijlyttle I changed the default archive format from zip to tar.gz. I guess it won't affect your use case (of GHE), but I just want to make sure. Thank you!

Comment (ijlyttle) [reply R/hugo.R:183]: Hi @yihui - sorry I have been "checked out" for a while - I will confirm!

Comment (yihui) [reply R/hugo.R:183]: No worries! (The earliest email that I haven't replied in my inbox was from Nov 2018, if that makes you feel better :)
